name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

 environment:
  name: amused-spontaneity / production

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Verificar secret de Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          if [ -z "$RAILWAY_TOKEN" ]; then
            echo "ERROR: RAILWAY_TOKEN está vacío"
            exit 1
          else
            echo "RAILWAY_TOKEN está disponible"
            echo "Longitud: ${#RAILWAY_TOKEN} caracteres"
          fi

      - name: Desplegar aplicación en Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service ci-cd-practica --environment production --ci